### PR TITLE
Updating privacy policies and company affiliations for multiple companies

### PR DESCRIPTION
**Pull request by billfitzgerald**
This pull request grew a bit larger than I originally anticipated. It pulls from some of the work described here: https://gist.github.com/billfitzgerald/50fc4750d1056b9c8873effbcb0d6783

It also covers the shift where [ViacomCBS is now Paramount Global](https://www.paramount.com/press/viacomcbs-unveils-new-company-name-global-content-slate-and-international-expansion-plans-for-paramount-at-investor-event).

I'm also attaching a spreadsheet for reference where I documented when I reviewed these services (this has been sitting for a while; just got round to the work over the weekend).
[needs_manual_processing.csv](https://github.com/duckduckgo/tracker-radar/files/8467384/needs_manual_processing.csv)

### CODE REVIEW

**Review by dharb — APPROVED** [review]
This is :rocket: as always, thank you @billfitzgerald! Apologies for the tardy review.

**Review by jdorweiler — APPROVED** [review]

**Comment by jdorweiler** [comment]
Thanks for doing this @billfitzgerald - There's just one conflict to fix, then I can merge this.

**Comment by billfitzgerald** [comment]
Shoot - Thanks for the review and the merge; I'll review the conflict and see if there are things I can adjust in my workflow to eliminate things like this for future PRs.

**Comment by jdorweiler** [comment]
No problem, I think you just need to pull in the latest entity changes from #129.

**Pull request merged**
