### PR TITLE
Cname data

### PR DESCRIPTION
**Pull request by Charlie-belmer**
This is data from a 5/21/2020 crawl with first party data and cname resolution enabled.

### CODE REVIEW

**Comment by mraakashshah** [comment]
Hi! I'm curious, what does "first party data and cname resolution enabled" mean for tracker detection?

**Comment by Charlie-belmer** [comment]
> Hi! I'm curious, what does "first party data and cname resolution enabled" mean for tracker detection?

We're extending detection to also include cases where third parties are delivering content via a DNS CNAME, which appears as a first party request. This should give a more comprehensive data set, as a small number of trackers deploy mostly behind CNAME's and were not previously represented correctly in our data set.

**Comment by kdzwinel** [comment]
BTW we just merged CNAME data in (https://github.com/duckduckgo/tracker-radar/releases/tag/2020.06). Should we close this PR?

**Comment by Charlie-belmer** [comment]
> BTW we just merged CNAME data in (https://github.com/duckduckgo/tracker-radar/releases/tag/2020.06). Should we close this PR?

Yes, this one is no longer needed - it was based on a smaller crawl than the June update.

**Pull request closed without merging**
