### PR TITLE
August 2022 update

### PR DESCRIPTION
**Pull request by muodov**
August update with enabled autoconsent opt-in.
Wiki (US): https://zok.pw/tracker-radar-wiki/
Wiki (DE): https://x.zok.pw/tracker-radar-wiki/de-aug-optin/index.html

### CODE REVIEW

**Review by jdorweiler — APPROVED** [review]

**Comment by kdzwinel** [comment]
We should update https://slayterdev.github.io/tracker-radar-wiki/ , any reason we didn't do that?

>Wiki (US): https://zok.pw/tracker-radar-wiki/

Trending Entities and New Entities look wrong to me 🤔 (new include Google, trending are empty)

**Comment by muodov** [comment]
@kdzwinel Wiki update PR is here https://github.com/SlayterDev/tracker-radar-wiki/pull/26
I rebuilt the wiki again from scratch and it looks correct now. It was probablly a local history caching problem during build. Thanks for catching that!

**Comment by kdzwinel** [comment]
Thanks for update @muodov ! I followed up on some domains that disappeared and it looks like they are actually gone from those sites, so it seems ok. We have one new big domain (3%+ prevalence) - [afcdn.net](https://zok.pw/tracker-radar-wiki/domains/afcdn.net.html), we should add entity information to it as a follow up. I suspect it's replacing https://zok.pw/tracker-radar-wiki/domains/ackcdn.net.html that, at the same time, lost 3% prevalence and it has a similar name (cc @dharb ). But yeah, not a blocker for this update 👍  Nicely done.

**Review by dharb — APPROVED** [review]
Looks good to me, thanks @muodov!

Thanks for calling out the afcdn.net domain @kdzwinel, tracking that [here](https://app.asana.com/0/0/1202884640466291/f) and will follow up with an ownership PR.

**Pull request merged**
