### PR TITLE
Updated domains from July crawl

### PR DESCRIPTION
**Pull request by jdorweiler**
Domain update from July crawler data. 
~Adds domain data for AU, CA, CH, DE, GB, NL, and NO regions.~ Saving this for the next update

### CODE REVIEW

**Comment by SlayterDev** [comment]
LGTM 👍

**Comment by SlayterDev** [comment]
Can't approve because its so big 😂

**Comment by dharb** [comment]
Not sure if it's an issue or not, but wanted to flag that US crawl stats went from [6963 domains and 1961 entities](https://github.com/duckduckgo/tracker-radar/blob/a930cb3c6c2bf1134b09cea1c5b0342b413a4864/build-data/generated/releasestats.txt) in May's crawl to [7415 domains and 2021 entities](https://github.com/duckduckgo/tracker-radar/blob/main/build-data/generated/releasestats.txt) in June's crawl to [42498 domains and 9113 entities](https://github.com/duckduckgo/tracker-radar/blob/jd/july-domains/build-data/generated/US/releasestats.txt) in this month's crawl.

**Comment by SlayterDev** [comment]
> Not sure if it's an issue or not, but wanted to flag that US crawl stats went from [6963 domains and 1961 entities](https://github.com/duckduckgo/tracker-radar/blob/a930cb3c6c2bf1134b09cea1c5b0342b413a4864/build-data/generated/releasestats.txt) in May's crawl to [7415 domains and 2021 entities](https://github.com/duckduckgo/tracker-radar/blob/main/build-data/generated/releasestats.txt) in June's crawl to [42498 domains and 9113 entities](https://github.com/duckduckgo/tracker-radar/blob/jd/july-domains/build-data/generated/US/releasestats.txt) in this month's crawl.

May - normal crawl
June - increased crawl size by 1.5x
July - Added subpages increasing crawl size by 2x

Likely the cause

**Comment by jdorweiler** [comment]
I think increasing the crawl size by 2x might explain Google prevalence increasing too.

**Comment by dharb** [comment]
I could be totally wrong here, but I would be very very surprised if the # of entities seen went up 4x due to crawling subpages. That would imply that crawling subpages produces over 7000 entities by itself, while crawling root domains only produces ~2000 entities. Seems worthwhile to me to generate a list of these 9113 entities to quickly review for accuracy.

**Comment by jdorweiler** [comment]
I see what happened. The generated entity prevalence is only for the last region that was processed. I'll reprocess the data to fix it.

**Comment by dharb** [comment]
Gotcha, thanks for investigating 👍 

One more thing while you're in there - mind updating entity files with latest prevalence data?

**Comment by jdorweiler** [comment]
Updated the data. Since we're crawling the root and one subdomain for each site I increased the minimum number of sites to be considered a common third party from 2 to 3 sites. That decreases the number of domains and entities, but this still a significant increase from the previous update. 

Here's the new entities found in this update
https://gist.github.com/jdorweiler/454f10135502b53db86d0e5c274438dc#file-newentities-txt

**Comment by kdzwinel** [comment]
> Since we're crawling the **root and one subdomain** for each site I increased the minimum number of sites to be considered a common third party from 2 to 3 sites.

AFAIK this is only true for the US region? Did you change that limit globally?

----

Can someone confirm that all of those points below are true? Checking if I understand everything correctly.

1. This is a first TR update that includes subpages
2. This is a first TR update that includes regions
3. For US we are doing 75k + subpages
4. For other regions we are doing 10k w/o subpages

----

https://github.com/duckduckgo/tracker-radar/blob/jd/july-domains/docs/DATA_MODEL.md

> The domain data is stored as individual region-specific JSON files. Within the domains directory are subdirectories which contain domain data files from each regional crawl. A listing of the regions crawled is below:

IMO we could expand a bit more on how we got this data. How about:

> "We crawl the most popular domains for given region from that region. Resulting domain data is stored in region-specific subdirectories within the `/domains` directory:"

**Comment by SlayterDev** [comment]
@kdzwinel Correct on all 4 points.

**Comment by jdorweiler** [comment]
I recrawled and updated the data.
I'm skipping subdomains and regional crawler data for this update, but left the US data in a regional domain directory. I expect to get all the regional data in the next update.

**Comment by kdzwinel** [comment]
Thanks a lot Jason for quickly resolving this 🙇‍♂️

Isn't it weird to have those links in docs that would now resolve to 404 (`domains/NO/`)? I'd at least drop a note in there:

> ⚠️ Regions other than US are not available in this crawl, but will be made available in the next one (August).

**Comment by jdorweiler** [comment]
Good point. I just removed the region links from the docs for now. It's easy enough to add those back in later.

**Pull request merged**
